name: snaphunt
description: SnapHunt - Flutter Philippines Hackathon 2019 Entry

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^0.4.0+9

  # realtime db
  cloud_firestore: ^0.12.9+5

  # ml
  firebase_ml_vision: ^0.9.2+2

  # auth
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7

  # di
  provider: ^3.1.0+1

  # qr
  qr_flutter: ^3.0.1
  flutter_barcode_scanner: ^0.1.7

  # camera feed
  camera: ^0.5.6+2
  path_provider: ^1.4.0

  # vibrator
  vibration: ^1.2.2

  # check connectivity
  connectivity: ^0.4.5+2

  # autosize text
  auto_size_text: ^2.1.0

  # local db
  hive: ^1.1.1

  # screenshot widget
  screenshot: ^0.1.1

  # share images
  esys_flutter_share: ^1.0.2

  expandable: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # wave
  wave: ^0.0.8

  flutter_staggered_animations: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/default.json
    - assets/top.png
    - assets/main.png
  
  fonts:
  - family: SF_Atarian_System
    fonts:
    - asset: assets/fonts/SF_Atarian_System.ttf
    - asset: assets/fonts/SF_Atarian_System_Bold.ttf
      weight: 700
